version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly", day: "monday", time: "08:00" }
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "/"
    schedule: { interval: "weekly", day: "monday", time: "08:15" }
    open-pull-requests-limit: 10
    allow: [ { dependency-type: "direct" } ]
  - package-ecosystem: "docker"
    directory: "/"
    schedule: { interval: "monthly", day: "monday", time: "09:00" }
    open-pull-requests-limit: 2
