name: QR URL Fallback
on:
  workflow_call:
  workflow_dispatch:

jobs:
  set-url:
    runs-on: ubuntu-latest
    steps:
      - name: Set SB_REPO_URL fallback
        run: |
          echo "SB_REPO_URL=https://08abbd3d-777f-4af5-b274-466c8cc1c573-00-1ko1zjf07c39i.riker.replit.dev" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY_URL=https://github.com/${{ github.repository }}" >> $GITHUB_ENV
