
name: Trivy (Supersonic)
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
permissions: { contents: read, security-events: write }
jobs:
  fs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
      - uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: 'trivy-results.sarif' }
