
name: OpenSSF Scorecard (Supersonic)
on:
  branch_protection_rule:
  schedule: [ { cron: '23 5 * * 3' } ]
  workflow_dispatch:
permissions: { contents: read, security-events: write, id-token: write }
jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: ossf/scorecard-action@v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: results.sarif }
